### ISSUE TITLE
Prerender returning undefined://example.com

### ISSUE THREAD

**Issue by jsantana90** [dfischer/meteor-prerenderio#23]
I've removed spiderable package and added this package to my angular-meteor app.

```json
{
  "public": {
  },
  "PrerenderIO": {
    "token": "mytoken"
  }
}
```

This is my settings.json file

![screenshot from 2016-03-04 09 40 39](https://cloud.githubusercontent.com/assets/9933887/13528572/31a8bf5a-e1ed-11e5-83f8-41407ea2157e.png)

after the `undefined://` it's my ip address from the server.

What am I doing wrong?

**Comment by dfischer** [comment]
Where's your token URL?

**Comment by juliancwirko** [comment]
hmm I think I have the same problem. I've provided my token in the settings.json file and deployed my app, but the 'Crawl stats' in the prerender.io admin panel shows something like:

```
undefined://127.0.0.1:3000/
```

This looks like the bots are sent to the localhost instead to the real url
