### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by jwaitze** [dfischer/meteor-prerenderio#32]
Lines:
`prerenderio.set('prerenderServiceUrl', 'http://localhost:3000/'));`
`prerenderio.set('prerenderToken', 'YOUR_TOKEN'));`

should instead be:
`prerenderio.set('prerenderServiceUrl', 'http://localhost:3000/');`
`prerenderio.set('prerenderToken', 'YOUR_TOKEN');`

**Comment by dfischer** [comment]
Thanks!
