### ISSUE TITLE
Question about where to place prerenderio.set('prerenderToken', 'YOUR_TOKEN'));

### ISSUE THREAD

**Issue by gcardella** [dfischer/meteor-prerenderio#8]
In our meteor app, do we place prerenderio.set('prerenderToken', 'YOUR_TOKEN')); inside the template's js file?

Per template:
Template.templateName.rendered = function() {
    prerenderio.set('prerenderToken', 'YOUR_TOKEN'));
};

Whole App:
Meteor.startup( function() {
  prerenderio.set('prerenderToken', 'YOUR_TOKEN'));
});

Is the prerenderio a global?

**Comment by superandrew213** [comment]
prerenderio.set('prerenderToken', 'YOUR_TOKEN'));

needs to be in the server code.
